# .github/workflows/1-stake-workflow.yml

name: Stake Monad Tokens

on:
  # این خط به شما اجازه می‌دهد که این عملیات را به صورت دستی هم برای تست اجرا کنید
  workflow_dispatch:
  
  schedule:
    # اجرا در ساعت 5:30 UTC (ساعت ۹:۰۰ صبح به وقت ایران) هر روز
    - cron: '30 5 * * *'

jobs:
  stake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install project dependencies (ethers.js)
        run: npm install

      - name: Execute the Stake Script
        run: node src/stake-script.js
        env:
          # کلید خصوصی را به صورت امن از سکرت‌های گیت‌هاب می‌خواند
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
